version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      timezone: Europe/Kiev
      time: "09:00"
    open-pull-requests-limit: 3