name: Node CI (Ubuntu/MacOS)

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # windows-latest is temp removed
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, bootstrap
      run: |
        npm i
        npm run bootstrap
    - name: npm lint, build, and test
      run: |
        npm ci
        npm run lint
        npm run build
        npm test
      env:
        CI: true
